device = "/dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event"

screen_width = 10370
screen_height = 6915
edge_tolerance = 15
min_distance = 300

[actions]
1_from_top = "bash /home/ewio/.config/rofi/status.sh"
1_from_bottom = "rofi -show"
1_from_right = "bspc desktop -f next.occupied.local"
1_from_left = "bspc desktop -f prev.occupied.local"
2_down = "bspc node -c"
2_right = "bspc node -d next; bspc desktop -f next"
2_left = "bspc node -d prev; bspc desktop -f prev"
