#! /bin/sh

bspc monitor HDMI-0 -d I II III
bspc monitor HDMI-1 -d IV V

bspc config window_gap		0

bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config border_width	1
bspc config single_monocle	true
bspc config normal_border_color \#2b3339
bspc config active_border_color \#2b3339
bspc config focused_border_color \#859289

bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Steam state=floating
bspc rule -a hl2_linux state=fullscreen
bspc rule -a '*:*:Plover' desktop=V


pgrep -x sxhkd > /dev/null || sxhkd &

xrdb .Xresources &

pulseaudio -D &

compton -b &

feh --bg-fill "$HOME/.config/bg.png"

"$HOME/.local/bin/plover.AppImage" &
