#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
actuator &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          0

bspc config normal_border_color \#282828

bspc config single_monocle      true
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a feh state=floating

feh --bg-fill /home/ewio/.config/bg.png

picom &
